#!/bin/sh
set -e
#perl -V > /dev/null 2>&1
#if [ $? -eq 0 ]; then
# perl /usr/bin/mindelmod.pl /etc/min.conf ModuleName=/usr/lib/min-ci-testsTestModule.so
#else
# echo "Can not remove test module from min.conf (need perl)\n"
#fi
