#ifndef MIN_DBUS_PLUGIN_COMMON_H
#define MIN_DBUS_PLUGIN_COMMON_H

#define MIN_SERVICE_NAME     "org.maemo.MIN"
#define MIN_SERVICE_OBJECT_PATH "/Min"
#define MIN_SERVICE_INTERFACE "org.maemo.MIN"

#endif /* MIN_DBUS_PLUGIN_COMMON_H */

